---
title: "Benjamin Trueman"
description: "Postdoctoral researcher  \nDepartment of Civil & Resource Engineering
  \ \nDalhousie University  \nHalifax, NS, CAN  \n"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Website: https://bentrueman.github.io  
Google Scholar: https://scholar.google.ca/citations?user=V1hY9TkAAAAJ&hl=en  

# Academic background    

2018 PhD, Civil Engineering  
Dalhousie University, Halifax, NS  
Thesis title: “Controlling Lead Release To Drinking Water: Impacts Of Iron Oxides, Complexing Species, Orthophosphate, And Lead Pipe Replacement”

2012 BSc, Environmental Science  
Dalhousie University, Halifax, NS  

# Skills  

- R programming (https://github.com/bentrueman) and data analysis (e.g., https://doi.org/10.26434/chemrxiv-2022-b3f72-v4)
- Geochemical modeling with applications in corrosion control
  - Developed an R package for predicting lead and copper solubility using PHREEQC, available at https://github.com/bentrueman/pbcusol
- Communication
  - Wrote or co-wrote more than 30 peer-reviewed journal articles
  - Presented at international academic conferences

# Journal articles 

1. **Trueman, B. F.**, Locsin, J. M., Doré, E., Hood, K., & Gagnon, G. A. (2022). Sodium silicate and hexametaphosphate promote the release of (oxyhydr)oxide nanoparticles from corroding iron. Environmental Science: Advances. (in press).
  
1. **Trueman, B. F.**, James, W., Shu, T., Doré, E., & Gagnon, G. A. (2022). Comparing corrosion control treatments using a robust Bayesian generalized additive model. ES&T Engineering. (in press).

1. Locsin, J. A., **Trueman, B. F.**, Doré, E., Bleasdale-Pollowy, A., & Gagnon, G. A. (2022). Impacts of orthophosphate-polyphosphate blends on the dissolution and transformation of lead (II) carbonate. Scientific Reports. (in press).

1. Gao, Y., **Trueman, B. F.**, & Gagnon, G. A. (2022). Early phase effects of silicate and orthophosphate on lead (Pb) corrosion scale development and Pb release. Journal of Environmental Management, 321, 115947. https://doi.org/10.1016/j.jenvman.2022.115947

1. King, P. W., Peldszus, S., Mishrra, A., **Trueman, B. F.**, Aghasadeghi, K., Gagnon G. A., Giammar, D. E., & Huck, P. M. Role of natural organic matter and hardness on lead release from galvanic corrosion. Environmental Science: Water Research & Technology. 8, 1687-1699. https://doi.org/10.1039/D1EW00903F  

1. Munoz, S., **Trueman, B. F.**, Li, B., & Gagnon, G. A. (2022). Effect of sodium silicate on drinking water biofilm development. Environmental Science: Water Research & Technology. 8, 1300-1311. https://doi.org/10.1039/D1EW00682G

1. **Trueman, B. F.**, Bleasdale-Pollowy, A., Locsin, J. A., Bennett, J. L., Krkošek, W. H., & Gagnon, G. A. (2021). Seasonal lead release into drinking water and the effect of aluminum. ACS ES&T Water. 2(5), 710–720. https://doi.org/10.1021/acsestwater.1c00320

1. Locsin, J. A., Hood, K. M., Doré, E., **Trueman, B. F.**,  & Gagnon, G. A. (2022). Colloidal lead in drinking water: Formation, occurrence, and characterization. Critical Reviews in Environmental Science and Technology. https://doi.org/10.1080/10643389.2022.2039549

1. Guardado, A. L. P., Sweeney, C. L., Hayes, E., **Trueman, B. F.**, Huang, Y., Jamieson, R. C., Rand, J. L., Gagnon, G. A., & Stoddart, A. K. (2022). Development and optimization of a new method for direct extraction of SARS-CoV-2 RNA from municipal wastewater using magnetic beads. Environmental Science: Water Research & Technology. 8, 47-61. https://doi.org/10.1039/D1EW00539A

1. Li, B., **Trueman, B. F.**, Doré, E., & Gagnon, G. A. (2021). Effectiveness of sodium silicates for lead corrosion control: a critical review of current data. Environmental Science & Technology Letters. 8(11), 932–939. https://doi.org/10.1021/acs.estlett.1c00671

1. **^a^Joint first author**: Anderson, L.E.,^a^ **Trueman, B. F.**,^a^ Dunnington, D.W.^a^ & Gagnon, G. A. (2021).  Relative importance of organic- and iron-based colloids in six Nova Scotian lakes. npj Clean Water 4, 26 https://doi.org/10.1038/s41545-021-00115-4

2.	Aghasadeghi, K., Peldszus, S., **Trueman, B. F.**, Mishrra, A., Cooke, M. G., Slawson, R. M., Giammar, D. E., Gagnon, G. A., & Huck, P. M. (2021). Pilot-scale comparison of sodium silicates, orthophosphate and pH adjustment to reduce lead release from lead service lines. Water Research. 195, 116955. https://doi.org/10.1016/j.watres.2021.116955

3.	**^a^Joint first author**: Redden, D.,^a^ **Trueman, B. F.**,^a^ Dunnington, D. W., Anderson, L. A., & Gagnon, G. A. (2021). Chemical recovery and browning of Nova Scotia surface waters in response to declining acid deposition. Environmental Science: Processes & Impacts. 23, 446-456. https://doi.org/10.1039/D0EM00425A

4.	Li, B., **Trueman, B. F.**, Locsin, J. A., Rahman, M. S., Gao, Y., Park, Y., & Gagnon, G. A. (2021). Impact of sodium silicate on lead release from lead carbonate. Environmental Science: Water Research & Technology. 7, 599-609. https://doi.org/10.1039/D0EW00886A

5.	Li, B., **Trueman, B. F.**, Rahman, M. S., & Gagnon, G. A. (2021). Controlling lead release due to uniform and galvanic corrosion—An evaluation of silicate-based inhibitors. Journal of Hazardous Materials, 407, 124707. https://doi.org/10.1016/j.jhazmat.2020.124707

6.	Li, B., **Trueman, B. F.**, Munoz, S., Locsin, J. M., & Gagnon, G. A. (2021). Impact of sodium silicate on lead release and colloid size distributions in drinking water. Water Research, 190, 116709. https://doi.org/10.1016/j.watres.2020.116709

7.	Dunnington, D. W., **Trueman, B. F.**, Raseman, W. J., Anderson, L. E., Gagnon, G. A. (2021). Comparing the Predictive Performance, Interpretability, and Accessibility of Machine Learning and Physically Based Models for Water Treatment. ACS ES&T Engineering. 1(3), 348–356. https://doi.org/10.1021/acsestengg.0c00053

8.	**^a^Joint first author**: Lane, K.,^a^ **Trueman, B. F.**,^a^ Locsin, J., Gagnon, G. A. (2020). Inorganic contaminants in Canadian First Nation community water systems. Journal of Water and Health. 18 (5), 728–740. https://doi.org/10.2166/wh.2020.185

9.	Locsin, J. M., **Trueman, B. F.**, Serracin-Pitti, D., Stanton, G. M. L., Gagnon, G. A. (2020). Potential regulatory implications of guideline changes in lead monitoring for Nova Scotia. AWWA Water Science, 2(4), e1182. https://doi.org/10.1002/aws2.1182

10.	Gora, S. L., Anaviapik-Soucie, T., Allward, N. E., Ontiveros, C. C., L’Hérault, V., Kunuk- Gavin, M., **Trueman, B. F.**, Campbell, J., Stoddart, A. K., Gagnon, G. A. (2020). Microbiological water quality in a decentralized Arctic drinking water system. Environmental Science: Water Research & Technology, 6, 1855-1868. https://doi.org/10.1039/d0ew00019a

11.	Gora, S. L., **Trueman, B. F.**, Anaviapik-Soucie, T., Gavin, M. K., Ontiveros, C. C., Campbell, J., L’Hérault, V., Stoddart, A. K., & Gagnon, G. A. (2020). Source Water Characteristics and Building-specific Factors Influence Corrosion and Point of Use Water Quality in a Decentralized Arctic Drinking Water System. Environmental Science & Technology, 54, 2192−2201. https://doi.org/10.1021/acs.est.9b04691

12.	**^a^Joint first author**: Brophy, M. J.,^a^ **Trueman, B. F.**,^a^ Park, Y., Betts, R. A., & Gagnon, G. A. (2019). Fluorescence Spectra Predict Microcystin-LR and Disinfection Byproduct Formation Potential in Lake Water. Environmental Science & Technology, 53(2), 586–594. https://doi.org/10.1021/acs.est.8b04139 (ACS Article on Request: https://pubs.acs.org/articlesonrequest/AOR-yzIje94pRCzeBYYfe6sd)

13.	Li, B., **Trueman, B. F.**, Rahman, M. S., Gao, Y., Park, Y., & Gagnon, G. A. (2019). Understanding the impacts of sodium silicate on water quality and iron oxide particles. Environmental Science: Water Research & Technology, 5(8), 1360–1370. https://doi.org/10.1039/C9EW00257J

14.	**Trueman, B. F.**, Anaviapik-Soucie, T., L’Hérault, V., & Gagnon, G. A. (2019). Characterizing colloidal metals in drinking water by field flow fractionation. Environmental Science: Water Research & Technology, 5(12), 2202–2209. https://doi.org/10.1039/C9EW00560A

15.	**Trueman, B. F.**, Gregory, B. S., McCormick, N. E., Gao, Y., Gora, S., Anaviapik-Soucie, T., L’Hérault, V., & Gagnon, G. A. (2019). Manganese Increases Lead Release to Drinking Water. Environmental Science & Technology, 53(9), 4803–4812. https://doi.org/10.1021/acs.est.9b00317

16.	Deshommes, E., **Trueman, B .F.**, Douglas, I., Huggins, D., Laroche, L., Swertfeger, J., Spielmacher, A., Gagnon, G. A., & Prévost, M. (2018). Lead Levels at the Tap and Consumer Exposure from Legacy and Recent Lead Service Line Replacements in Six Utilities. Environmental Science & Technology, 52(16), 9451–9459. https://doi.org/10.1021/acs.est.8b02388

17.	Gao, Y., **Trueman, B. F.**, Stoddart, A. K., & Gagnon, G. A. (2018). Understanding the Impact of Extracellular Polymeric Substances on Lead Release in Drinking Water Systems. ACS Omega, 3(11), 14824–14832. https://doi.org/10.1021/acsomega.8b02363

18.	**Trueman, B. F.**, Krkošek, W. H., & Gagnon, G. A. (2018). Effects of ortho- and polyphosphates on lead speciation in drinking water. Environmental Science: Water Research & Technology, 4(4), 505–512. https://doi.org/10.1039/C7EW00521K

19.	Anderson, L. E., Krkošek, W. H., Stoddart, A. K., **Trueman, B. F.**, & Gagnon, G. A. (2017). Lake Recovery Through Reduced Sulfate Deposition: A New Paradigm for Drinking Water Treatment. Environmental Science & Technology, 51(3), 1414–1422. https://doi.org/10.1021/acs.est.6b04889

20.	**Trueman, B. F.**, Sweet, G. A., Harding, M. D., Estabrook, H., Bishop, D. P., & Gagnon, G. A. (2017). Galvanic Corrosion of Lead by Iron (Oxyhydr)Oxides: Potential Impacts on Drinking Water Quality. Environmental Science & Technology, 51(12), 6812–6820. https://doi.org/10.1021/acs.est.7b01671

21.	**Trueman, B. F.**, Camara, E., & Gagnon, G. A. (2016). Evaluating the Effects of Full and Partial Lead Service Line Replacement on Lead Levels in Drinking Water. Environmental Science & Technology, 50(14), 7389–7396. https://doi.org/10.1021/acs.est.6b01912

22.	**Trueman, B. F.**, & Gagnon, G. A. (2016a). A new analytical approach to understanding nanoscale lead-iron interactions in drinking water distribution systems. Journal of Hazardous Materials, 311, 151–157. https://doi.org/10.1016/j.jhazmat.2016.03.001

23.	**Trueman, B. F.**, MacIsaac, S. A., Stoddart, A. K., & Gagnon, G. A. (2016). Prediction of disinfection by-product formation in drinking water via fluorescence spectroscopy. Environmental Science: Water Research & Technology, 2(2), 383–389. https://doi.org/10.1039/C5EW00285K

24.	**Trueman, B. F.**, & Gagnon, G. A. (2016b). Understanding the Role of Particulate Iron in Lead Release to Drinking Water. Environmental Science & Technology, 50(17), 9053–9060. https://doi.org/10.1021/acs.est.6b01153

25.	Pei, W. W., Xie, X., Ong, P., **Trueman, B. F.**, McVicar, M. A., Walsh, M. E., & Gagnon, G. A. (2013). Water Reclamation and Reuse. Water Environment Research, 85(10), 1308–1321. https://doi.org/10.2175/106143013X13698672322183

# Preprints  

1. **Trueman, B. F.**, Locsin, J. M., Doré, E., Hood, K., & Gagnon, G. A. (2022). Sodium silicate and hexametaphosphate promote the release of (oxyhydr)oxide nanoparticles from corroding iron. ChemRxiv. https://doi.org/10.26434/chemrxiv-2022-rtzqm-v3
  
1. **Trueman, B. F.**, James, W., Shu, T., Doré, E., & Gagnon, G. A. (2022). Comparing corrosion control treatments using a robust Bayesian generalized additive model. ChemRxiv. https://doi.org/10.26434/chemrxiv-2022-b3f72-v4

1. Locsin, J. A., **Trueman, B. F.**, Doré, E., Bleasdale-Pollowy, A., & Gagnon, G. A. (2022). Impacts of orthophosphate-polyphosphate blends on the dissolution and transformation of lead (II) carbonate. ChemRxiv. https://doi.org/10.26434/chemrxiv-2022-2g0j3-v2

1. Gao, Y., **Trueman, B. F.**, & Gagnon, G. A. (2022). Early Phase Effects of Silicate and Orthophosphate on Lead (Pb) Corrosion Scale Development and Pb Release. SSRN. http://dx.doi.org/10.2139/ssrn.4127245

1. **Trueman, B. F.**, Bleasdale-Pollowy, A., Locsin, J. A., Bennett, J. L., Krkošek, W. H., & Gagnon, G. A. (2021). Seasonal lead release to drinking water and the effect of aluminum. ChemRxiv. https://doi.org/10.26434/chemrxiv-2021-59nd6-v4

2. Munoz, S., **Trueman, B. F.** Li, B., & Gagnon, G. A. (2021). Effect of sodium silicate on drinking water biofilm development. bioRxiv. https://doi.org/10.1101/2021.09.15.460503

3. Guardado, A. L. P., Sweeney, C. L., Hayes, E., **Trueman, B. F.**, Huang, Y., Jamieson, R. C., Rand, J. L., Gagnon, G. A., & Stoddart, A. K. (2020). Development and optimization of a new method for direct extraction of SARS-CoV-2 RNA from municipal wastewater using magnetic beads. medRxiv. https://doi.org/10.1101/2020.12.04.20237230

# First author conference presentations

1. Trueman, B. F., Locsin, J., Doré, E., Hood, K., & Gagnon, G. A. 2022. Colloids and nanoparticles in drinking water: a review of occurrence and new data on the role of sequestrants. American Chemical Society National Meeting & Expo, August 21--25 in Chicago, Il. 

1.	Trueman, B. F., Stoddart,  A. K.,  & Gagnon, G. A. 2019. Complexation of metals in drinking water systems by NOM. Oral presentation. The 7th IWA Specialist Conference on Natural Organic Matter in Water, October 7--9 in Tokyo, Japan.

2.	Trueman, B. F., Anderson, L. A., & Gagnon, G. A. 2019. NOM, cyanobacteria and algal toxins: monitoring tools and predictive modeling of contaminant occurrence in drinking water supplies. Oral presentation. The 7th IWA Specialist Conference on Natural Organic Matter in Water, October 7--9 in Tokyo, Japan.

3.	Trueman, B. F., Dunnington, D. & Gagnon, G. A. 2019. Communicating water quality data using the grammar of graphics. Poster presentation. American Chemical Society National Meeting & Expo, August 25--29 in San Diego, CA. 

4.	Trueman, B. F., Brophy, M., Anderson, L. A., Park, Y. & Gagnon, G. A. 2019. Fluorescence spectra predict microcystin-LR occurrence in lake water. Oral presentation. 3rd Interdisciplinary Freshwater Harmful Algal Blooms Workshop, April 24--26 in Toronto, Canada.

5.	Trueman, B. F., Locsin, J., Krkošek, W. H., & Gagnon, G. A. 2018. Understanding lead complexation through corrosion control with phosphate-based inhibitors. Oral presentation. American Water Works Association Water Quality Technology Conference, November 11--14 in Toronto, Canada.

6.	Trueman, B. F., Krkošek, W. H., & Gagnon, G. A. 2018. Effects of ortho- and polyphosphates on lead speciation in drinking water. Oral presentation. American Chemical Society Annual Conference, March 18--22, in New Orleans, LA.

7.	Trueman, B. F. & Gagnon, G. A. 2017. Galvanic corrosion of lead by iron (oxyhydr)oxides: potential impacts on drinking water quality. Oral presentation. American Chemical Society Annual Conference, August 20--24, in Washington, DC.

8.	Trueman, B. F. & Gagnon, G. A. 2017. Evaluating strategies for controlling lead release to drinking water. Oral presentation. American Water Works Association International Symposium on Inorganics, March 21--22 in Detroit, MI. 

9.	Trueman, B. F. & Gagnon, G. A. 2016. Understanding the role of iron particles in lead release to drinking water. Poster presentation. American Water Works Association Water Quality Technology Conference, November 13--17 in Indianapolis, IN.

10.	Trueman, B. F., MacIsaac, S. A., Stoddart, A. K., & Gagnon, G. A. 2016. Prediction of disinfection byproduct formation in drinking water via fluorescence spectroscopy. Oral presentation. 17th National Conference on Drinking Water, October 16--18 in Ottawa, Canada.

11.	Trueman, B. F. & Gagnon, G. A. 2016. Understanding lead contamination in drinking water systems. Oral presentation. Atlantic Canadian Water Works Association Annual Conference, September 18--21, in Moncton, Canada.

12.	Trueman, B. F. & Gagnon, G. A. 2016. Understanding the role of colloidal particles in lead release to drinking water. Oral presentation. American Chemical Society Annual Conference, August 21--25 in Philadelphia, PA.

13.	Trueman, B. F. & Gagnon, G. A. 2015. Controlling lead in drinking water: phosphate inhibition, lead service line replacement, and the role of the water main. Oral presentation. Atlantic Canadian Water Works Association Annual Conference, October 4--7 in St. John's, Canada.

14.	Trueman, B. F., Woods, J., Gagnon, G. A., & Castleden, H. 2014. The effect of partial lead service line replacement and the barriers to full replacement. Oral presentation. American Water Works Association Annual Conference, June 8--12 in Boston, MA.

15.	Trueman, B. F. & Gagnon, G. A. 2014. The effect of cast iron water mains on lead release to standing water. Oral presentation. Canadian Society for Civil Engineering Environmental Specialty Conference, May 28--31 in Halifax, Canada.

16.	Trueman, B. F. & Gagnon, G. A. 2013. Optimization of phosphate dose following residential sampling for lead. Poster presentation. American Water Works Association Annual Conference and Exposition, June 9--13 in Denver, CO.

# Reports

Prepared confidential consulting reports on topics in drinking water quality and treatment for the cities of Regina, Saint John, and Halifax and for Health Canada and Nova Scotia Environment.

# Peer-reviewer

- Water Research
- Environmental Science & Technology
- Environmental Science & Technology Letters
- ACS Earth and Space Chemistry
- Corrosion Science
- Journal of Hazardous Materials
- Environmental Science: Water Research & Technology
- Environmental Science: Processes & Impacts
- Environmental Pollution
- Springer Nature Applied Sciences

# Awards  

- 2021 Mitacs Accelerate Grant ($110,000 over 2 years)
- 2019	Best presentation award, The 7th IWA Specialist Conference on Natural Organic Matter (Tokyo, Japan)
- 2017 	Nova Scotia Graduate Scholarship
- 2015	NSERC Post Graduate Scholarship Doctoral Level
- 2015	President’s Award, Dalhousie University

