---
title: "*UPDATE:* non-parametric matched pair testing with left-censored data"
description: |
  An alternative (Bayesian) approach using brms.
author:
  - name: Ben Trueman
    url: {}
date: 12-27-2021
output:
  distill::distill_article:
    self_contained: false
draft: true
---

```{r setup, include=FALSE}
here::i_am("2021-12-27-update-non-parametric-matched-pair-testing-with-left-censored-data/update-non-parametric-matched-pair-testing-with-left-censored-data.Rmd")
knitr::opts_chunk$set(echo = FALSE)
library("tidyverse")
library("brms")
theme_set(theme_bw())
```

```{r load}
helsel <- read_csv(
  here::here("2021-07-05-non-parametric-matched-pair-testing-with-left-censored-data/helsel_table_9.7 copy.csv")
) %>% 
  mutate(
    across(
      c(june, september), 
      ~ if_else(str_detect(.x, "^<"), -1, 0),
      .names = "cen_{.col}"
    ),
    across(c(june, september), ~ as.numeric(str_remove(.x, "<")))
  )
```

```{r plot}

helsel %>%
  ggplot(aes(june, september)) + 
  geom_point(
    data = function(x) {
      x %>% 
        filter(if_all(starts_with("cen_"), ~ .x == 0))
    }
  ) + 
  geom_segment(
    data = function(x) {
      x %>% 
        filter(cen_june == -1 & cen_september == 0)
    },
    aes(x = 0, xend = june, y = september, yend = september)
  ) +
  geom_segment(
    data = function(x) {
      x %>% 
        filter(cen_june == 0 & cen_september == -1)
    },
    aes(x = june, xend = june, y = 0, yend = september)
  ) +
  geom_rect(
    data = function(x) {
      x %>% 
        filter(cen_june == -1 & cen_september == -1) %>% 
        # this works because censoring limits are all the same for these data
        distinct(june, september) 
    },
    aes(xmin = 0, ymin = 0, xmax = june, ymax = september),
    alpha = .5
  ) +
  scale_x_log10() +
  scale_y_log10() + 
  geom_abline() +
  labs(
    x = expression("June atrazine concentration (µg L"^-1*")"),
    y = expression("September atrazine concentration (µg L"^-1*")")
  )

```

```{r model}

model_in <- helsel %>% 
  pivot_longer()

model <- brms::brm(
  bf()
)

helsel

```


